[msx] test Started org.apache.hadoop.hdfs.server.namenode.TestCheckpoint#testCheckpointWithSeparateDirsAfterNameFails
[msx] unitTestCounterInClass = 0
2020-03-14 06:50:28,902 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 06:50:29,664 [main] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 06:50:30,770 [main] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 34654 start
2020-03-14 06:50:31,909 [main] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 34654 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Failure org.apache.hadoop.hdfs.server.namenode.TestCheckpoint#testCheckpointWithSeparateDirsAfterNameFails
[msx] writeFile testName = org.apache.hadoop.hdfs.server.namenode.TestCheckpoint#testCheckpointWithSeparateDirsAfterNameFails
[msx] failed
[msx] failureMessage: Did not fail to checkpoint when there are no valid storage dirs
[msx] stackTrace: java.lang.AssertionError: Did not fail to checkpoint when there are no valid storage dirs
2020-03-14 06:50:31,965 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 06:50:31,967 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.hdfs.server.namenode.TestCheckpoint#testCheckpointWithSeparateDirsAfterNameFails
[msx] writeFile testName = org.apache.hadoop.hdfs.server.namenode.TestCheckpoint#testCheckpointWithSeparateDirsAfterNameFails
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.hdfs.server.namenode.TestCheckpoint#testCheckpointWithSeparateDirsAfterNameFails
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
