[msx] test Started org.apache.hadoop.net.TestNetworkTopology#testChooseRandomExcludedNode
[msx] unitTestCounterInClass = 0
[msx] test Failure org.apache.hadoop.net.TestNetworkTopology#testChooseRandomExcludedNode
[msx] writeFile testName = org.apache.hadoop.net.TestNetworkTopology#testChooseRandomExcludedNode
[msx] failed
[msx] failureMessage: null
[msx] stackTrace: java.lang.AssertionError
2020-03-14 09:04:09,582 [main] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 09:04:09,592 [main] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 09:04:09,594 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.net.TestNetworkTopology#testChooseRandomExcludedNode
[msx] writeFile testName = org.apache.hadoop.net.TestNetworkTopology#testChooseRandomExcludedNode
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.net.TestNetworkTopology#testChooseRandomExcludedNode
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
