[msx] test Started org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureToleration#testVolumeAndTolerableConfiguration
[msx] unitTestCounterInClass = 0
2020-03-14 07:43:42,021 [Thread-0] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 07:43:42,713 [Thread-0] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 07:43:43,717 [Thread-0] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 43467 start
2020-03-14 07:43:43,733 [Thread-0] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 07:43:43,804 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:43:44,136 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 39248 start
2020-03-14 07:43:44,790 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 39248 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:43:44,862 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:43:44,912 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 40665 start
2020-03-14 07:43:45,145 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 40665 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:43:45,196 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:43:45,263 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 37969 start
2020-03-14 07:43:45,402 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 37969 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:43:45,450 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:43:45,497 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 44048 start
2020-03-14 07:43:45,610 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 44048 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:43:45,757 [Thread-0] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 43467 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Failure org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureToleration#testVolumeAndTolerableConfiguration
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureToleration#testVolumeAndTolerableConfiguration
[msx] failed
[msx] failureMessage: expected:<false> but was:<true>
[msx] stackTrace: java.lang.AssertionError: expected:<false> but was:<true>
2020-03-14 07:43:45,830 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureToleration#testVolumeAndTolerableConfiguration
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureToleration#testVolumeAndTolerableConfiguration
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailureToleration#testVolumeAndTolerableConfiguration
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
