[msx] test Started org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDataNodeFailToStartWithVolumeFailure
[msx] unitTestCounterInClass = 0
2020-03-14 07:37:56,374 [Thread-0] INFO  namenode.NameNode (NameNode.java:<clinit>(931)) - [msx-restart] reconfPoint = 0
2020-03-14 07:37:57,123 [Thread-0] INFO  namenode.NameNode (NameNode.java:performReconfig(958)) - [msx-restart] NameNode init, reconfigMode is none, do nothing
2020-03-14 07:37:58,130 [Thread-0] INFO  namenode.NameNode (NameNode.java:<init>(1042)) - [msx-restart] NameNode 39733 start
2020-03-14 07:37:58,144 [Thread-0] INFO  datanode.DataNode (DataNode.java:<clinit>(433)) - [msx-restart] reconfPoint = 0
2020-03-14 07:37:58,214 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:37:58,552 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 35666 start
2020-03-14 07:37:58,566 [Thread-0] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:37:58,732 [Thread-0] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 42481 start
2020-03-14 07:37:59,436 [Thread-119] INFO  datanode.DataNode (DataNode.java:performReconfig(460)) - [msx-restart] DataNode init, reconfigMode is none, do nothing
2020-03-14 07:37:59,481 [Thread-119] INFO  datanode.DataNode (DataNode.java:runDatanodeDaemon(2750)) - [msx-restart] DataNode 44045 start
2020-03-14 07:37:59,707 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 44045 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:37:59,762 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 42481 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:37:59,789 [Thread-0] INFO  datanode.DataNode (DataNode.java:shutdown(2075)) - [msx-restart] DataNode 35666 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
2020-03-14 07:37:59,925 [Thread-0] INFO  namenode.NameNode (NameNode.java:stop(1087)) - [msx-restart] NameNode 39733 stop, double check before stop, dfs.data.transfer.client.tcpnodelay = true
[msx] test Failure org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDataNodeFailToStartWithVolumeFailure
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDataNodeFailToStartWithVolumeFailure
[msx] failed
[msx] failureMessage: Failed to get expected IOException
[msx] stackTrace: java.lang.AssertionError: Failed to get expected IOException
2020-03-14 07:37:59,999 [main] INFO  server.JournalNode (JournalNode.java:<clinit>(168)) - [msx-restart] reconfPoint = 0
[msx] reset performed
[msx] test Finished org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDataNodeFailToStartWithVolumeFailure
[msx] writeFile testName = org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDataNodeFailToStartWithVolumeFailure
[msx] Info : file existed /root/parameter_test_controller/shared/test_results/org.apache.hadoop.hdfs.server.datanode.TestDataNodeVolumeFailure#testDataNodeFailToStartWithVolumeFailure
[msx] succeed
[msx] reset performed
[msx] all testRunFinished
